name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, ':bookmark:')"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ secrets.GH_BOILERZ_BOT_TOKEN }}

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_BOILERZ_BOT_TOKEN }}

      - uses: boilerz/action-release@master
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_BOILERZ_BOT_TOKEN }}
